version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "nileshkumar"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      python-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "nileshkumar"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      frontend-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      nextjs-ecosystem:
        patterns:
          - "next"
          - "@next/*"
          - "eslint-config-next"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "nileshkumar"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "nileshkumar"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"