# Enterprise-grade Docker Compose build configuration
# Following 2024-2025 best practices

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.enterprise
      target: ${BUILD_TARGET:-production}
      args:
        - PYTHON_VERSION=${PYTHON_VERSION:-3.12}
        - POETRY_VERSION=${POETRY_VERSION:-1.7.1}
      cache_from:
        - type=registry,ref=${DOCKER_REGISTRY:-docker.io}/${DOCKER_IMAGE:-prism-backend}:buildcache
      cache_to:
        - type=registry,ref=${DOCKER_REGISTRY:-docker.io}/${DOCKER_IMAGE:-prism-backend}:buildcache,mode=max
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
        - ${DOCKER_REGISTRY:-docker.io}/${DOCKER_IMAGE:-prism-backend}:${VERSION:-latest}
        - ${DOCKER_REGISTRY:-docker.io}/${DOCKER_IMAGE:-prism-backend}:${GIT_COMMIT:-latest}
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_IMAGE:-prism-backend}:${VERSION:-latest}
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
    deploy:
      replicas: ${REPLICAS:-2}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s