# External Secrets Operator configuration for production
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prism-secrets
  namespace: prism
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore  # Use cluster-wide store in prod
  target:
    name: prism-secrets
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "{{ .database_url }}"
        JWT_SECRET: "{{ .jwt_secret }}"
        REDIS_URL: "{{ .redis_url }}"
        QDRANT_URL: "{{ .qdrant_url }}"
        QDRANT_API_KEY: "{{ .qdrant_api_key }}"
        SENTRY_DSN: "{{ .sentry_dsn }}"
        OPENAI_API_KEY: "{{ .openai_api_key }}"
        ANTHROPIC_API_KEY: "{{ .anthropic_api_key }}"
  data:
    - secretKey: database_url
      remoteRef:
        key: prism/prod/db
        property: url
    - secretKey: jwt_secret
      remoteRef:
        key: prism/prod/auth
        property: jwt_secret
    - secretKey: redis_url
      remoteRef:
        key: prism/prod/cache
        property: url
    - secretKey: qdrant_url
      remoteRef:
        key: prism/prod/vector
        property: url
    - secretKey: qdrant_api_key
      remoteRef:
        key: prism/prod/vector
        property: api_key
    - secretKey: sentry_dsn
      remoteRef:
        key: prism/prod/monitoring
        property: sentry_dsn
    - secretKey: openai_api_key
      remoteRef:
        key: prism/prod/ai
        property: openai_api_key
    - secretKey: anthropic_api_key
      remoteRef:
        key: prism/prod/ai
        property: anthropic_api_key
---
# Database credentials with rotation
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: prism
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    template:
      type: postgresql.cnpg.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: prism/prod/db
        property: username
    - secretKey: password
      remoteRef:
        key: prism/prod/db
        property: password
        version: "latest"  # Enable automatic rotation
---
# Redis credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: prism
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: redis-credentials
    template:
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: prism/prod/cache
        property: password
---
# Qdrant credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qdrant-credentials
  namespace: prism
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qdrant-credentials
    template:
      data:
        api-key: "{{ .api_key }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: prism/prod/vector
        property: api_key
---
# Backup credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-backup-credentials
  namespace: prism
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-backup-credentials
    template:
      data:
        ACCESS_KEY_ID: "{{ .access_key_id }}"
        SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
  data:
    - secretKey: access_key_id
      remoteRef:
        key: prism/prod/backup
        property: aws_access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: prism/prod/backup
        property: aws_secret_access_key