apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prism-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prism
  source:
    repoURL: https://github.com/nilukush/prism-core
    targetRevision: staging
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: prism-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        environment: staging
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  info:
  - name: "Environment"
    value: "Staging"
  - name: "Owner"
    value: "Platform Team"
  - name: "Slack"
    value: "#prism-staging"