apiVersion: v2
name: prism
description: PRISM - Open Source AI Agent Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - agents
  - platform
  - orchestration
home: https://github.com/nilukush/prism-core
sources:
  - https://github.com/nilukush/prism-core
maintainers:
  - name: PRISM Team
    email: team@prism.io
icon: https://raw.githubusercontent.com/nilukush/prism-core/main/logo.png
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of PRISM Helm chart
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
    - url: https://artifacthub.io/packages/helm/bitnami/redis
  artifacthub.io/signKey: |
    fingerprint: 1234567890ABCDEF1234567890ABCDEF12345678
    url: https://keybase.io/prismteam/pgp_keys.asc
dependencies:
  - name: postgresql
    version: "~13.2.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
  - name: redis
    version: "~18.6.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache