apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prism-staging

commonLabels:
  environment: staging
  app.kubernetes.io/version: staging

resources:
  - ../../base
  - namespace.yaml
  - secrets.yaml
  - postgres-staging.yaml
  - redis-staging.yaml
  - qdrant-staging.yaml

patches:
  - target:
      kind: Deployment
      name: prism-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: staging
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: INFO

  - target:
      kind: HorizontalPodAutoscaler
      name: prism-api
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5

  - target:
      kind: Ingress
      name: prism-api
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api-staging.prism.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api-staging.prism.example.com

  # Enable canary with 10% traffic
  - target:
      kind: Ingress
      name: prism-api-canary
    patch: |-
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1canary-weight
        value: "10"
      - op: replace
        path: /spec/rules/0/host
        value: api-staging.prism.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api-staging.prism.example.com

  # Moderate resources for staging
  - target:
      kind: Deployment
      name: prism-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi

images:
  - name: prism/prism-api
    newTag: staging-latest

configMapGenerator:
  - name: prism-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
      - LOG_FORMAT=json
      - CORS_ALLOWED_ORIGINS=https://staging.prism.example.com