apiVersion: v1
kind: Namespace
metadata:
  name: prism-staging
  labels:
    app.kubernetes.io/name: prism
    app.kubernetes.io/environment: staging
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted