# Staging Redis configuration
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: prism-staging
spec:
  replicas: 2  # 2 instances for staging
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - name: redis-exporter
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp3
      resources:
        requests:
          storage: 5Gi
---
# Staging PDB - allow 1 disruption
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-pdb
  namespace: prism-staging
spec:
  minAvailable: 1